### EDA Remote Work: ¿Revolución o Ilusión? · Stack Overflow Developer Survey 2022 & 2025

In [17]:
# Setup del entorno
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración estética
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
pd.set_option('display.max_columns', 100)

print("Setup completo ✓")

Setup completo ✓

In [18]:
import pandas as pd

# Mostrar TODAS las columnas, sin truncar
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)

In [48]:
# Cargar ambos años por separado
df_2022 = pd.read_csv('src/data/survey_results_2022.csv', low_memory=False)
df_2025 = pd.read_csv('src/data/survey_results_2025.csv', low_memory=False)

print(f"2022: {df_2022.shape}")
print(f"2025: {df_2025.shape}")

2022: (73268, 79)
2025: (49191, 172)

### Primera Exploración

In [49]:
# Ver las primeras filas del 2021
df_2022.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write code sometimes as part of my work","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;Friend or family member;Other online resources (e.g., videos, blogs, foru...",Technical documentation;Blogs;Programming Games;Written Tutorials;Stack Overflow,NaN,14,5,"Data scientist or machine learning specialist;Developer, front-end;Engineer, data;Engineer, site...",20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern Ireland,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., depression, bipolar disorder, etc.);I have an anxiety...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., University, College, etc)",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosting service web GUI;Dedicated version control GUI a...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, forum);School (i.e., University, College, etc);On t...",Technical documentation;Blogs;Stack Overflow;Online books;Video-based Online Courses;Online chal...,NaN,8,3,"Developer, front-end;Developer, full-stack;Developer, back-end;Developer, desktop or enterprise ...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities like Stack Overflow,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Server;Firebase Realtime Database,Cloud Firestore;Elasticsearch;Firebase Realtime Database;Redis,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow for Teams (private knowledge sharing & collaboratio...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [50]:
# Ver las primeras filas del 2025
df_2025.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive ...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific deve...,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my co...,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security an...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Other online resources (e.g. standard...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Sla...",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lis...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search ...,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns abou...,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn b...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-employed",None of the above,10.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Videos (not associated with specific ...,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or sys...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or industry involuntarily,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI GPT (chatbot models),Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models),Gemini (Flash general purpose models);openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year","Chat (people);Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Testing code;Creating or maintaining documentation;Lea...,NaN,Project planning;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Se...,Learning about a codebase;Writing code;Generating content or synthetic data,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI...,AI agents have improved the quality of my code.;AI agents have helped me solve complex problems ...,AI agents have improved collaboration within my team.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tool...,NaN,I am concerned about the accuracy of the information provided by AI agents.;Integrating AI agent...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn b...,"Understand how things actually work, problem solving, and algorithms",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated wi...","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certif...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and moni...,Learning about a codebase;Writing code;Debugging or fixing code;Predictive analytics,Search for answers;Generating content or synthetic data;Learning new concepts or technologies,NaN,"AI solutions that are almost right, but not quite;I don’t use AI tools regularly",NO,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about new technologies or codebases.,AI agents have increased my productivity.;AI agents have improved the quality of my code.;AI age...,AI agents have helped me automate repetitive tasks.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns abou...,Integrating AI agents with my existing tools and workflows can be difficult.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I have ethical or...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-employed","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn new coding techniques or programming languages",NaN,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",Technical documentation (is generated for/by the tool or system);Other online resources (e.g. st...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source and is currently used by more than just myself but n...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;PowerShell;Python;SQL;TypeScript;VBA;Visual Basic (...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;Redis;SQLite,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Maven (build tool);MSBuild;npm;NuGet;Pip,Amazon Web Services (AWS);APT;Docker;Maven (build tool);MSBuild;npm;NuGet;Pip,Amazon Web Services (AWS);APT;Docker;Maven (build tool);MSBuild;npm;NuGet;Pip,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,"Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debugging or fixing code;Search for answers;Learning new ...,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and moni...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and...,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns abou...,It takes significant time and effort to learn how to use AI agents effectively.;The cost of usin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the task correctly",60000.0,7.0

In [51]:
# Ver cuántas columnas tiene realmente
print(f"Total columnas 2022: {df_2022.shape[1]}")
print(f"Total columnas 2025: {df_2025.shape[1]}")

# Ver la lista completa de nombres
print("\n=== Columnas 2022 ===")
print(df_2022.columns.tolist())

print("\n=== Columnas 2025 ===")
print(df_2025.columns.tolist())

Total columnas 2022: 79
Total columnas 2025: 172

=== Columnas 2022 ===
['ResponseId', 'MainBranch', 'Employment', 'RemoteWork', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency', 'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use', 'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction', 'VCHostingPersonal use', 'VCHostingProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith', 'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity', 'Accessibility', 'MentalHealth', 'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering', 'Onboarding', 'ProfessionalTech', 'TrueFalse_1', 'TrueFalse_2', 'TrueFalse_3', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly']

=== Columnas 2025 ===
['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow', 'YearsCode', 'DevType', 'OrgSize', 'ICorPM', 'RemoteWork', 'PurchaseInfluence', 'TechEndorseIntro', 'TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4', 'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8', 'TechEndorse_9', 'TechEndorse_13', 'TechEndorse_13_TEXT', 'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5', 'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13', 'TechOppose_16', 'TechOppose_15', 'TechOppose_15_TEXT', 'Industry', 'JobSatPoints_1', 'JobSatPoints_2', 'JobSatPoints_3', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'JobSatPoints_13', 'JobSatPoints_14', 'JobSatPoints_15', 'JobSatPoints_16', 'JobSatPoints_15_TEXT', 'AIThreat', 'NewRole', 'ToolCountWork', 'ToolCountPersonal', 'Country', 'Currency', 'CompTotal', 'LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry', 'DatabaseChoice', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'DatabaseHaveEntry', 'DatabaseWantEntry', 'PlatformChoice', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'PlatformHaveEntry', 'PlatformWantEntry', 'WebframeChoice', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'WebframeHaveEntry', 'WebframeWantEntry', 'DevEnvsChoice', 'DevEnvsHaveWorkedWith', 'DevEnvsWantToWorkWith', 'DevEnvsAdmired', 'DevEnvHaveEntry', 'DevEnvWantEntry', 'SOTagsHaveWorkedWith', 'SOTagsWantToWorkWith', 'SOTagsAdmired', 'SOTagsHaveEntry', 'SOTagsWant Entry', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired', 'OfficeStackHaveEntry', 'OfficeStackWantEntry', 'CommPlatformHaveWorkedWith', 'CommPlatformWantToWorkWith', 'CommPlatformAdmired', 'CommPlatformHaveEntr', 'CommPlatformWantEntr', 'AIModelsChoice', 'AIModelsHaveWorkedWith', 'AIModelsWantToWorkWith', 'AIModelsAdmired', 'AIModelsHaveEntry', 'AIModelsWantEntry', 'SOAccount', 'SOVisitFreq', 'SODuration', 'SOPartFreq', 'SO_Dev_Content', 'SO_Actions_1', 'SO_Actions_16', 'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6', 'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15', 'SO_Actions_15_TEXT', 'SOComm', 'SOFriction', 'AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIToolCurrently partially AI', "AIToolDon't plan to use AI for this task", 'AIToolPlan to partially use AI', 'AIToolPlan to mostly use AI', 'AIToolCurrently mostly AI', 'AIFrustration', 'AIExplain', 'AIAgents', 'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral', 'AIAgentImpactSomewhat agree', 'AIAgentImpactNeutral', 'AIAgentImpactSomewhat disagree', 'AIAgentImpactStrongly agree', 'AIAgentImpactStrongly disagree', 'AIAgentChallengesNeutral', 'AIAgentChallengesSomewhat disagree', 'AIAgentChallengesStrongly agree', 'AIAgentChallengesSomewhat agree', 'AIAgentChallengesStrongly disagree', 'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat']

In [52]:
# Info general del 2022
df_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  str
 2   Employment                      71709 non-null  str
 3   RemoteWork                      58958 non-null  str
 4   CodingActivities                58899 non-null  str
 5   EdLevel                         71571 non-null  str
 6   LearnCode                       71580 non-null  str
 7   LearnCodeOnline                 50685 non-null  str
 8   LearnCodeCoursesCert            29389 non-null  str
 9   YearsCode                       71331 non-null  str
 10  YearsCodePro                    51833 non-null  str
 11  DevType                         61302 non-null  str
 12  OrgSize                         51039 non-null  str
 13  PurchaseInfluence               50969 non-null  str
 14  BuyNewTool                      67963 non-null  str
 15  Country                         71771 non-null  str
 16  Currency                        51264 non-null  str
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  str
 19  LanguageHaveWorkedWith          70975 non-null  str
 20  LanguageWantToWorkWith          67027 non-null  str
 21  DatabaseHaveWorkedWith          60121 non-null  str
 22  DatabaseWantToWorkWith          51014 non-null  str
 23  PlatformHaveWorkedWith          49924 non-null  str
 24  PlatformWantToWorkWith          40415 non-null  str
 25  WebframeHaveWorkedWith          53544 non-null  str
 26  WebframeWantToWorkWith          46122 non-null  str
 27  MiscTechHaveWorkedWith          44992 non-null  str
 28  MiscTechWantToWorkWith          36810 non-null  str
 29  ToolsTechHaveWorkedWith         54171 non-null  str
 30  ToolsTechWantToWorkWith         46566 non-null  str
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  str
 32  NEWCollabToolsWantToWorkWith    64108 non-null  str
 33  OpSysProfessional use           65503 non-null  str
 34  OpSysPersonal use               70963 non-null  str
 35  VersionControlSystem            71379 non-null  str
 36  VCInteraction                   68156 non-null  str
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  str
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  str
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  str
 42  OfficeStackSyncWantToWorkWith   47688 non-null  str
 43  Blockchain                      71071 non-null  str
 44  NEWSOSites                      71365 non-null  str
 45  SOVisitFreq                     70961 non-null  str
 46  SOAccount                       71572 non-null  str
 47  SOPartFreq                      58229 non-null  str
 48  SOComm                          71408 non-null  str
 49  Age                             70946 non-null  str
 50  Gender                          70853 non-null  str
 51  Trans                           70315 non-null  str
 52  Sexuality                       66565 non-null  str
 53  Ethnicity                       69474 non-null  str
 54  Accessibility                   67244 non-null  str
 55  MentalHealth                    66447 non-null  str
 56  TBranch                         52670 non-null  str
 57  ICorPM                          36283 non-null  str
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  str
 60  Knowledge_2                     34973 non-null  str
 61  Knowledge_3                     35133 non-null  str
 62  Knowledge_4                     35097 non-null  str
 63  Knowledge_5                     35014 non-null  str
 64  Knowledge_6                     34991 non-null  str
 65  Knowledge_7                     34977 non-null  str
 66  Frequency_1                     35371 non-null  str
 67  Frequency_2                     35344 non-null  str
 68  Frequency_3                     34515 non-null  str
 69  TimeSearching                   36198 non-null  str
 70  TimeAnswering                   36022 non-null  str
 71  Onboarding                      35679 non-null  str
 72  ProfessionalTech                34906 non-null  str
 73  TrueFalse_1                     35819 non-null  str
 74  TrueFalse_2                     35715 non-null  str
 75  TrueFalse_3                     35749 non-null  str
 76  SurveyLength                    70444 non-null  str
 77  SurveyEase                      70508 non-null  str
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), str(73)
memory usage: 44.2 MB

In [53]:
# Info general del 2025
df_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [54]:
print(list(df_2025.columns))

['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow', 'YearsCode', 'DevType', 'OrgSize', 'ICorPM', 'RemoteWork', 'PurchaseInfluence', 'TechEndorseIntro', 'TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4', 'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8', 'TechEndorse_9', 'TechEndorse_13', 'TechEndorse_13_TEXT', 'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5', 'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13', 'TechOppose_16', 'TechOppose_15', 'TechOppose_15_TEXT', 'Industry', 'JobSatPoints_1', 'JobSatPoints_2', 'JobSatPoints_3', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'JobSatPoints_13', 'JobSatPoints_14', 'JobSatPoints_15', 'JobSatPoints_16', 'JobSatPoints_15_TEXT', 'AIThreat', 'NewRole', 'ToolCountWork', 'ToolCountPersonal', 'Country', 'Currency', 'CompTotal', 'LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry', 'DatabaseChoice', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'DatabaseHaveEntry', 'DatabaseWantEntry', 'PlatformChoice', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'PlatformHaveEntry', 'PlatformWantEntry', 'WebframeChoice', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'WebframeHaveEntry', 'WebframeWantEntry', 'DevEnvsChoice', 'DevEnvsHaveWorkedWith', 'DevEnvsWantToWorkWith', 'DevEnvsAdmired', 'DevEnvHaveEntry', 'DevEnvWantEntry', 'SOTagsHaveWorkedWith', 'SOTagsWantToWorkWith', 'SOTagsAdmired', 'SOTagsHaveEntry', 'SOTagsWant Entry', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired', 'OfficeStackHaveEntry', 'OfficeStackWantEntry', 'CommPlatformHaveWorkedWith', 'CommPlatformWantToWorkWith', 'CommPlatformAdmired', 'CommPlatformHaveEntr', 'CommPlatformWantEntr', 'AIModelsChoice', 'AIModelsHaveWorkedWith', 'AIModelsWantToWorkWith', 'AIModelsAdmired', 'AIModelsHaveEntry', 'AIModelsWantEntry', 'SOAccount', 'SOVisitFreq', 'SODuration', 'SOPartFreq', 'SO_Dev_Content', 'SO_Actions_1', 'SO_Actions_16', 'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6', 'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15', 'SO_Actions_15_TEXT', 'SOComm', 'SOFriction', 'AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIToolCurrently partially AI', "AIToolDon't plan to use AI for this task", 'AIToolPlan to partially use AI', 'AIToolPlan to mostly use AI', 'AIToolCurrently mostly AI', 'AIFrustration', 'AIExplain', 'AIAgents', 'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral', 'AIAgentImpactSomewhat agree', 'AIAgentImpactNeutral', 'AIAgentImpactSomewhat disagree', 'AIAgentImpactStrongly agree', 'AIAgentImpactStrongly disagree', 'AIAgentChallengesNeutral', 'AIAgentChallengesSomewhat disagree', 'AIAgentChallengesStrongly agree', 'AIAgentChallengesSomewhat agree', 'AIAgentChallengesStrongly disagree', 'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat']

In [55]:
df_2025.info(verbose=True, show_counts=True) 
# Con los anteriores métodos no podíamos ver todas las columnas, así que utilizamos un parámetro oculto
# llamado verbose, Pandas decide automáticamente si colapsar la información o no según el tamaño. 
# Si lo pones en True, lo obligas a desglosarlo.

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 172 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    ResponseId                                49191 non-null  int64
 1    MainBranch                                49191 non-null  str
 2    Age                                       49191 non-null  str
 3    EdLevel                                   48149 non-null  str
 4    Employment                                48339 non-null  str
 5    EmploymentAddl                            44875 non-null  str
 6    WorkExp                                   42893 non-null  float64
 7    LearnCodeChoose                           46858 non-null  str
 8    LearnCode                                 33556 non-null  str
 9    LearnCodeAI                               45201 non-null  str
 10   AILearnHow                                28257 non-null  str
 11   YearsCode                                 43042 non-null  float64
 12   DevType                                   43680 non-null  str
 13   OrgSize                                   34178 non-null  str
 14   ICorPM                                    33243 non-null  str
 15   RemoteWork                                33780 non-null  str
 16   PurchaseInfluence                         37437 non-null  str
 17   TechEndorseIntro                          37556 non-null  str
 18   TechEndorse_1                             35975 non-null  float64
 19   TechEndorse_2                             35975 non-null  float64
 20   TechEndorse_3                             35975 non-null  float64
 21   TechEndorse_4                             35975 non-null  float64
 22   TechEndorse_5                             35975 non-null  float64
 23   TechEndorse_6                             35975 non-null  float64
 24   TechEndorse_7                             35975 non-null  float64
 25   TechEndorse_8                             35975 non-null  float64
 26   TechEndorse_9                             35975 non-null  float64
 27   TechEndorse_13                            35975 non-null  float64
 28   TechEndorse_13_TEXT                       2009 non-null   str
 29   TechOppose_1                              34259 non-null  float64
 30   TechOppose_2                              34259 non-null  float64
 31   TechOppose_3                              34259 non-null  float64
 32   TechOppose_5                              34259 non-null  float64
 33   TechOppose_7                              34259 non-null  float64
 34   TechOppose_9                              34259 non-null  float64
 35   TechOppose_11                             34259 non-null  float64
 36   TechOppose_13                             34259 non-null  float64
 37   TechOppose_16                             34259 non-null  float64
 38   TechOppose_15                             34259 non-null  float64
 39   TechOppose_15_TEXT                        1647 non-null   str
 40   Industry                                  33642 non-null  str
 41   JobSatPoints_1                            24943 non-null  float64
 42   JobSatPoints_2                            24943 non-null  float64
 43   JobSatPoints_3                            24943 non-null  float64
 44   JobSatPoints_4                            24943 non-null  float64
 45   JobSatPoints_5                            24943 non-null  float64
 46   JobSatPoints_6                            24943 non-null  float64
 47   JobSatPoints_7                            24943 non-null  float64
 48   JobSatPoints_8                            24943 non-null  float64
 49   JobSatPoints_9                            24943 non-null  float64
 50   JobSatPoints_10                           24943 non-null  float64
 51   JobSatPoints_11                           24943 non-null  float64
 52   JobSatPoints_13                           24943 non-null  float64
 53   JobSatPoints_14                           24943 non-null  float64
 54   JobSatPoints_15                           24943 non-null  float64
 55   JobSatPoints_16                           24943 non-null  float64
 56   JobSatPoints_15_TEXT                      664 non-null    str
 57   AIThreat                                  36078 non-null  str
 58   NewRole                                   35527 non-null  str
 59   ToolCountWork                             27611 non-null  float64
 60   ToolCountPersonal                         25582 non-null  float64
 61   Country                                   35437 non-null  str
 62   Currency                                  35437 non-null  str
 63   CompTotal                                 24866 non-null  float64
 64   LanguageChoice                            32214 non-null  str
 65   LanguageHaveWorkedWith                    31671 non-null  str
 66   LanguageWantToWorkWith                    27079 non-null  str
 67   LanguageAdmired                           23470 non-null  str
 68   LanguagesHaveEntry                        3982 non-null   str
 69   LanguagesWantEntry                        3150 non-null   str
 70   DatabaseChoice                            31688 non-null  str
 71   DatabaseHaveWorkedWith                    25550 non-null  str
 72   DatabaseWantToWorkWith                    19733 non-null  str
 73   DatabaseAdmired                           17295 non-null  str
 74   DatabaseHaveEntry                         2150 non-null   str
 75   DatabaseWantEntry                         1533 non-null   str
 76   PlatformChoice                            31262 non-null  str
 77   PlatformHaveWorkedWith                    24258 non-null  str
 78   PlatformWantToWorkWith                    19415 non-null  str
 79   PlatformAdmired                           17822 non-null  str
 80   PlatformHaveEntry                         3957 non-null   str
 81   PlatformWantEntry                         3100 non-null   str
 82   WebframeChoice                            31193 non-null  str
 83   WebframeHaveWorkedWith                    22992 non-null  str
 84   WebframeWantToWorkWith                    17639 non-null  str
 85   WebframeAdmired                           15709 non-null  str
 86   WebframeHaveEntry                         3294 non-null   str
 87   WebframeWantEntry                         2630 non-null   str
 88   DevEnvsChoice                             31079 non-null  str
 89   DevEnvsHaveWorkedWith                     26019 non-null  str
 90   DevEnvsWantToWorkWith                     20614 non-null  str
 91   DevEnvsAdmired                            19492 non-null  str
 92   DevEnvHaveEntry                           2762 non-null   str
 93   DevEnvWantEntry                           2112 non-null   str
 94   SOTagsHaveWorkedWith                      17922 non-null  str
 95   SOTagsWantToWorkWith                      13587 non-null  str
 96   SOTagsAdmired                             12240 non-null  str
 97   SOTagsHaveEntry                           458 non-null    str
 98   SOTagsWant Entry                          430 non-null    str
 99   OpSysPersonal use                         31417 non-null  str
 100  OpSysProfessional use                     28883 non-null  str
 101  OfficeStackAsyncHaveWorkedWith            29858 non-null  str
 102  OfficeStackAsyncWantToWorkWith            23206 non-null  str
 103  OfficeStackAsyncAdmired                   22208 non-null  str
 104  OfficeStackHaveEntry                      2589 non-null   str
 105  OfficeStackWantEntry                      1617 non-null   str
 106  CommPlatformHaveWorkedWith                30065 non-null  str
 107  CommPlatformWantToWorkWith                23351 non-null  str
 108  CommPlatformAdmired                       22877 non-null  str
 109  CommPlatformHaveEntr                      1476 non-null   str
 110  CommPlatformWantEntr                      1184 non-null   str
 111  AIModelsChoice                            30239 non-null  str
 112  AIModelsHaveWorkedWith                    16281 non-null  str
 113  AIModelsWantToWorkWith                    11845 non-null  str
 114  AIModelsAdmired                           11284 non-null  str
 115  AIModelsHaveEntry                         776 non-null    str
 116  AIModelsWantEntry                         475 non-null    str
 117  SOAccount                                 32797 non-null  str
 118  SOVisitFreq                               32710 non-null  str
 119  SODuration                                32627 non-null  str
 120  SOPartFreq                                32228 non-null  str
 121  SO_Dev_Content                            22836 non-null  str
 122  SO_Actions_1                              26260 non-null  float64
 123  SO_Actions_16                             24340 non-null  float64
 124  SO_Actions_3                              26260 non-null  float64
 125  SO_Actions_4                              26260 non-null  float64
 126  SO_Actions_5                              26260 non-null  float64
 127  SO_Actions_6                              26260 non-null  float64
 128  SO_Actions_9                              26260 non-null  float64
 129  SO_Actions_7                              26260 non-null  float64
 130  SO_Actions_10                             26260 non-null  float64
 131  SO_Actions_15                             26260 non-null  float64
 132  SO_Actions_15_TEXT                        823 non-null    str
 133  SOComm                                    31706 non-null  str
 134  SOFriction                                30787 non-null  str
 135  AISelect                                  33720 non-null  str
 136  AISent                                    33467 non-null  str
 137  AIAcc                                     33297 non-null  str
 138  AIComplex                                 33283 non-null  str
 139  AIToolCurrently partially AI              21028 non-null  str
 140  AIToolDon't plan to use AI for this task  25381 non-null  str
 141  AIToolPlan to partially use AI            22556 non-null  str
 142  AIToolPlan to mostly use AI               12818 non-null  str
 143  AIToolCurrently mostly AI                 11225 non-null  str
 144  AIFrustration                             31522 non-null  str
 145  AIExplain                                 26586 non-null  str
 146  AIAgents                                  31919 non-null  str
 147  AIAgentChange                             31678 non-null  str
 148  AIAgent_Uses                              12320 non-null  str
 149  AgentUsesGeneral                          5805 non-null   str
 150  AIAgentImpactSomewhat agree               10146 non-null  str
 151  AIAgentImpactNeutral                      9675 non-null   str
 152  AIAgentImpactSomewhat disagree            5791 non-null   str
 153  AIAgentImpactStrongly agree               6687 non-null   str
 154  AIAgentImpactStrongly disagree            3779 non-null   str
 155  AIAgentChallengesNeutral                  21295 non-null  str
 156  AIAgentChallengesSomewhat disagree        12125 non-null  str
 157  AIAgentChallengesStrongly agree           23108 non-null  str
 158  AIAgentChallengesSomewhat agree           21947 non-null  str
 159  AIAgentChallengesStrongly disagree        9314 non-null   str
 160  AIAgentKnowledge                          3401 non-null   str
 161  AIAgentKnowWrite                          766 non-null    str
 162  AIAgentOrchestration                      3760 non-null   str
 163  AIAgentOrchWrite                          478 non-null    str
 164  AIAgentObserveSecure                      2692 non-null   str
 165  AIAgentObsWrite                           264 non-null    str
 166  AIAgentExternal                           8332 non-null   str
 167  AIAgentExtWrite                           859 non-null    str
 168  AIHuman                                   29194 non-null  str
 169  AIOpen                                    22540 non-null  str
 170  ConvertedCompYearly                       23947 non-null  float64
 171  JobSat                                    26670 non-null  float64
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

##### Columnas clave del proyecto

In [60]:
# Vamos a verificar que las columnas que necesitamos para las 3 dimensiones existen en ambos años
cols_clave = ['RemoteWork', 'ConvertedCompYearly', 'YearsCodePro',
              'LanguageHaveWorkedWith', 'Country']

print("=== 2022 ===")
for col in cols_clave:
    existe = col in df_2022.columns
    print(f"  {col}: {'✓ existe' if existe else '✗ NO existe'}")

print("\n=== 2025 ===")
for col in cols_clave:
    existe = col in df_2025.columns
    print(f"  {col}: {'✓ existe' if existe else '✗ NO existe'}")

=== 2022 ===
  RemoteWork: ✓ existe
  ConvertedCompYearly: ✓ existe
  YearsCodePro: ✓ existe
  LanguageHaveWorkedWith: ✓ existe
  Country: ✓ existe

=== 2025 ===
  RemoteWork: ✓ existe
  ConvertedCompYearly: ✓ existe
  YearsCodePro: ✗ NO existe
  LanguageHaveWorkedWith: ✓ existe
  Country: ✓ existe

In [64]:
# Buscar columnas que puedan equivaler a 'YearsCodePro' en 2025 (Mide los años de experiencia)
print("\n=== Columnas con 'code' en 2025 ===")
print([c for c in df_2025.columns if 'code' in c.lower()])

print("\n=== Columnas con 'work' en 2025 ===")
print([c for c in df_2025.columns if 'work' in c.lower()])

print("\n=== Columnas con 'exp' en 2025 ===")
print([c for c in df_2025.columns if 'exp' in c.lower()])

=== Columnas con 'code' en 2025 ===
['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'YearsCode']

=== Columnas con 'work' en 2025 ===
['WorkExp', 'RemoteWork', 'ToolCountWork', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'DevEnvsHaveWorkedWith', 'DevEnvsWantToWorkWith', 'SOTagsHaveWorkedWith', 'SOTagsWantToWorkWith', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'CommPlatformHaveWorkedWith', 'CommPlatformWantToWorkWith', 'AIModelsHaveWorkedWith', 'AIModelsWantToWorkWith']

=== Columnas con 'exp' en 2025 ===
['WorkExp', 'AIExplain']

In [65]:
# Antes de renombrar, hay que asegurarse de que ambas columnas miden lo mismo.

# Ver qué tipo de valores tiene WorkExp en 2025
print("=== WorkExp (2025) ===")
print(df_2025['WorkExp'].describe())
print(f"\nTipo: {df_2025['WorkExp'].dtype}")
print(f"\nMuestra: {df_2025['WorkExp'].head(10).tolist()}")

# Comparar con YearsCodePro de 2022
print("\n=== YearsCodePro (2022) ===")
print(df_2022['YearsCodePro'].describe())
print(f"\nTipo: {df_2022['YearsCodePro'].dtype}")
print(f"\nMuestra: {df_2022['YearsCodePro'].head(10).tolist()}")

=== WorkExp (2025) ===
count    42893.000000
mean        13.367403
std         10.800117
min          1.000000
25%          5.000000
50%         10.000000
75%         20.000000
max        100.000000
Name: WorkExp, dtype: float64

Tipo: float64

Muestra: [8.0, 2.0, 10.0, 4.0, 21.0, 15.0, 9.0, 22.0, 9.0, 7.0]

=== YearsCodePro (2022) ===
count     51833
unique       52
top           3
freq       4261
Name: YearsCodePro, dtype: object

Tipo: str

Muestra: [nan, nan, '5', '17', '3', nan, nan, nan, '6', '30']